version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: coink_postgres
    environment:
      POSTGRES_USER: coink
      POSTGRES_PASSWORD: coink123
      POSTGRES_DB: coink_usuarios
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  api:
    build:
      context: ./src/Coink.Usuarios.API
      dockerfile: Dockerfile
    container_name: coink_api
    depends_on:
      - postgres
    ports:
      - "7151:7151"
    environment:
      ConnectionStrings__DefaultConnection: "Host=postgres;Port=5432;Database=coink_usuarios;Username=coink;Password=coink123"
